### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Gabriele69** [tim-sueberkrueb/switch#1]
Hello Tim, congratulation for your excellent game. Make transated this app so make it even more intetesting!

**Comment by timsueberkrueb** [comment]
Hey @GabrieleMartelli, thanks for your feature request! I'm glad you like it.

**Comment by timsueberkrueb** [comment]
Switch is now [on Transifex](https://www.transifex.com/tim-sueberkrueb/switch/).
